### PR TITLE
adding moead_gen to the python libraries with bfe support

### PR DESCRIPTION
**Pull request by kirbyherm**
As title, adding the moead_gen algorithm to the python bindings. I placed it in expose_algorithms_1.cpp rather than *_0.cpp since other bfe algorithms were located there. 

Should be good to go as far as I can tell. 

If you can review and accept so it can be deployed via conda, etc. I would appreciate it.

Thanks!

### CODE REVIEW

**Comment by kirbyherm** [comment]
@bluescarni @darioizzo Do either of you have any idea what the errors in the checks are from? On my own computer I get the errors even when I revert to both pagmo2 and pygmo2 compilations from source that do not include the moead_gen algorithm.

Any suggestions are welcome!

**Comment by kirbyherm** [comment]
unsure why these builds are failing, I'm able to compile from source on my machine and run the tests with no errors...

**Comment by astrojuanlu** [comment]
Looks like these test failures are also present in `master`, see gh-114.

**Comment by astrojuanlu** [comment]
@kirbyherm Could you rebase this on top of `master` and force push, or merge `master` and push? So the CI runs again

**Comment by kirbyherm** [comment]
sorry i kinda messed this up by pushing the `dill=0.3.5.1` change here and in #116, i think this can just be merged from here and #116 closed unless you'd like the `dill` changes to be on a separate PR

**Comment by darioizzo** [comment]
Thanks @kirbyherm this is now merged and will be released in 2.19 soon.

**Pull request merged**
