### PR TITLE
Trigger CI

### PR DESCRIPTION
**Pull request by astrojuanlu**
See if gh-112 and gh-113 CI failures are reproducible in current `master`.

### CODE REVIEW

**Comment by astrojuanlu** [comment]
cc @kirbyherm, let's see how this turns out.

**Comment by astrojuanlu** [comment]
Indeed, `master` is currently broken.

**Comment by bluescarni** [comment]
@astrojuanlu  @kirbyherm I think this is an issue triggered by an update in ``dill``. I'll investigate over the weekend.

**Comment by astrojuanlu** [comment]
Indeed, looks like `dill<0.3.6` fixed the problems on 3.8 at least.

**Comment by bluescarni** [comment]
@astrojuanlu Thanks for checking this out. Not sure what the best course of action is.

IIRC ``dill`` support was originally introduced after a user reported that ``cloudpickle`` (the default serialisation backend in pygmo) was failing on some types. Thus I added the option to switch to ``dill`` as an alternative. I don't think the selectable serialisation backend feature is being employed by many users, so my first instinct would be to just disable the ``dill`` testing in the test suite.

The alternative is to chase this with upstream...

**Comment by astrojuanlu** [comment]
The proper solution would indeed be trying to report this upstream, but looks like a massive rabbit hole I don't have time to get in. Temporarily capping `dill` at `<0.3.6` for the time being so at least the CI can pass can be a good short-term solution.

**Comment by bluescarni** [comment]
As mentioned in #115, let's just pin dill for the time being. I'll be closing this one.

**Pull request closed without merging**
